# common/codes.py

# Protocol version
PROTOCOL_VERSION = 1

# Message types
TYPE_GET_WEIGHT = 1
TYPE_GET_QUANTITY = 2
TYPE_ADD_ELEMENT = 3
TYPE_RESPONSE = 16

# Flags
FLAG_ERROR = 1  # Bit 0 set = error response

# Error codes
ERR_MISSING_FIELD = 100
ERR_NOT_FOUND = 101
ERR_DUPLICATE = 102
ERR_INVALID_WEIGHT = 103
ERR_INVALID_NAME = 104
ERR_BAD_CRC = 200
ERR_BAD_VERSION = 300
ERR_BAD_TYPE = 301
ERR_MALFORMED_PAYLOAD = 400
